=== DFIRKuiper/Kuiper/kuiper/app/parsers/vol_Parser/volatility/schemas/schema-6.1.0.json
{
  "$schema": "http://json-schema.org/schema#",
  "id": "http://volatilityfoundation.org/intermediate-format/schema",
  "title": "Symbol Container",
  "type": "object",
  "definitions": {
    "metadata_producer": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "version": {
          "type": "string"
        },
        "datetime": {
          "type": "string",
          "format": "date-time"
        }
      }
    },
    "metadata_windows_pe": {
      "type": "object",
      "properties": {
        "major": {
          "type": "integer"
        },
        "minor": {
          "type": "integer"
        },
        "revision": {
          "type": "integer"
        },
        "build": {
          "type": "integer"
        }
      },
      "additionalProperties": false,
      "required": [
        "major",
        "minor",
        "revision"
      ]
    },
    "metadata_windows_pdb": {
      "type": "object",
      "properties": {
        "GUID": {
          "type": "string"
        },
        "age": {
          "type": "integer"
        },
        "database": {
          "type": "string"
        },
        "machine_type": {
          "type": "integer"
        }
      },
      "additionalProperties": false,
      "required": [
        "GUID",
        "age",
        "database",
        "machine_type"
      ]
    },
    "metadata_windows": {
      "type": "object",
      "properties": {
        "pe": {
          "$ref": "#/definitions/metadata_windows_pe"
        },
        "pdb": {
          "$ref": "#/definitions/metadata_windows_pdb"
        }
      },
      "additionalProperties": false
    },
    "metadata_linux": {
      "type": "object",
      "$comment": "Reserved for future use"
    },
    "metadata_format": {
      "type": "string",
      "pattern": "^6.[0-9]+.[0-9]+$"
    },
    "metadata_source": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string"
        }
      }
    },
    "element_metadata": {
      "type": "object",
      "oneOf": [
        {
          "properties": {
            "format": {
              "$ref": "#/definitions/metadata_format"
            },
            "producer": {
              "$ref": "#/definitions/metadata_producer"
            }
          },
          "required": [
            "format"
          ],
          "additionalProperties": false
        },
        {
          "properties": {
            "format": {
              "$ref": "#/definitions/metadata_format"
            },
            "producer": {
              "$ref": "#/definitions/metadata_producer"
            },
            "windows": {
              "$ref": "#/definitions/metadata_windows"
            }
          },
          "required": [
            "format",
            "windows"
          ],
          "additionalProperties": false
        },
        {
          "properties": {
            "format": {
              "$ref": "#/definitions/metadata_format"
            },
            "producer": {
              "$ref": "#/definitions/metadata_producer"
            },
            "linux": {
              "$ref": "#/definitions/metadata_linux"
            }
          },
          "required": [
            "format",
            "linux"
          ],
          "additionalProperties": false
        }
      ]
    },
    "element_enum": {
      "properties": {
        "size": {
          "type": "integer"
        },
        "base": {
          "type": "string"
        },
        "constants": {
          "type": "object",
          "additionalProperties": {
            "type": "integer"
          }
        }
      },
      "required": [
        "size",
        "base",
        "constants"
      ],
      "additionalProperties": false
    },
    "element_symbol": {
      "properties": {
        "address": {
          "type": "number"
        },
        "linkage_name": {
          "type": "string"
        },
        "type": {
          "$ref": "#/definitions/type_descriptor"
        },
        "constant_data": {
          "type": "string",
          "media": {
            "binaryEncoding": "base64",
            "readOnly": true
          }
        }
      },
      "required": [
        "address"
      ],
      "additionalProperties": false
    },
    "element_base_type": {
      "properties": {
        "size": {
          "type": "integer"
        },
        "signed": {
          "type": "boolean"
        },
        "kind": {
          "type": "string",
          "pattern": "^(void|int|float|char|bool)$"
        },
        "endian": {
          "type": "string",
          "pattern": "^(little|big)$"
        }
      },
      "required": [
        "size",
        "kind",
        "signed",
        "endian"
      ],
      "additionalProperties": false
    },
    "element_user_type": {
      "properties": {
        "kind": {
          "type": "string",
          "pattern": "^(struct|union|class)$"
        },
        "size": {
          "type": "integer"
        },
        "fields": {
          "type": "object",
          "additionalProperties": {
            "$ref": "#/definitions/field"
          }
        }
      },
      "required": [
        "kind",
        "size",
        "fields"
      ],
      "additionalProperties": false
    },
    "field": {
      "properties": {
        "type": {
          "$ref": "#/definitions/type_descriptor"
        },
        "offset": {
          "type": "integer"
        }
      },
      "required": [
        "type",
        "offset"
      ],
      "additionalProperties": false
    },
    "type_descriptor": {
      "oneOf": [
        {
          "$ref": "#/definitions/type_pointer"
        },
        {
          "$ref": "#/definitions/type_base"
        },
        {
          "$ref": "#/definitions/type_array"
        },
        {
          "$ref": "#/definitions/type_struct"
        },
        {
          "$ref": "#/definitions/type_enum"
        },
        {
          "$ref": "#/definitions/type_function"
        },
        {
          "$ref": "#/definitions/type_bitfield"
        }
      ]
    },
    "type_pointer": {
      "properties": {
        "kind": {
          "type": "string",
          "pattern": "^pointer$"
        },
        "base": {
          "type": "string"
        },
        "subtype": {
          "$ref": "#/definitions/type_descriptor"
        }
      },
      "required": [
        "kind",
        "subtype"
      ],
      "additionalProperties": false
    },
    "type_base": {
      "properties": {
        "kind": {
          "type": "string",
          "pattern": "^base$"
        },
        "name": {
          "type": "string"
        }
      },
      "required": [
        "kind",
        "name"
      ],
      "additionalProperties": false
    },
    "type_array": {
      "properties": {
        "kind": {
          "type": "string",
          "pattern": "^array$"
        },
        "subtype": {
          "$ref": "#/definitions/type_descriptor"
        },
        "count": {
          "type": "integer"
        }
      },
      "required": [
        "kind",
        "subtype",
        "count"
      ],
      "additionalProperties": false
    },
    "type_struct": {
      "properties": {
        "kind": {
          "type": "string",
          "pattern": "^(struct|class|union)$"
        },
        "name": {
          "type": "string"
        }
      },
      "required": [
        "kind",
        "name"
      ],
      "additionalProperties": false
    },
    "type_enum": {
      "properties": {
        "kind": {
          "type": "string",
          "pattern": "^enum$"
        },
        "name": {
          "type": "string"
        }
      },
      "required": [
        "kind",
        "name"
      ],
      "additionalProperties": false
    },
    "type_function": {
      "properties": {
        "kind": {
          "type": "string",
          "pattern": "^function$"
        }
      },
      "required": [
        "kind"
      ],
      "additionalProperties": false
    },
    "type_bitfield": {
      "properties": {
        "kind": {
          "type": "string",
          "pattern": "^bitfield$"
        },
        "bit_position": {
          "type": "integer"
        },
        "bit_length": {
          "type": "integer"
        },
        "type": {
          "oneOf": [
            {
              "$ref": "#/definitions/type_base"
            },
            {
              "$ref": "#/definitions/type_enum"
            }
          ]
        }
      },
      "required": [
        "kind",
        "bit_position",
        "bit_length",
        "type"
      ],
      "additionalProperties": false
    }
  },
  "properties": {
    "metadata": {
      "$ref": "#/definitions/element_metadata"
    },
    "base_types": {
      "additionalProperties": {
        "$ref": "#/definitions/element_base_type"
      }
    },
    "user_types": {
      "additionalProperties": {
        "$ref": "#/definitions/element_user_type"
      }
    },
    "enums": {
      "additionalProperties": {
        "$ref": "#/definitions/element_enum"
      }
    },
    "symbols": {
      "additionalProperties": {
        "$ref": "#/definitions/element_symbol"
      }
    }
  },
  "required": [
    "metadata",
    "base_types",
    "user_types",
    "enums",
    "symbols"
  ],
  "additionalProperties": false
}

=== DFIRKuiper/Kuiper/kuiper/app/parsers/vol_Parser/volatility/framework/symbols/windows/netscan-win10-x64.json
{
    "base_types": {
        "unsigned long": {
            "kind": "int",
            "size": 4,
            "signed": false,
            "endian": "little"
        },
        "unsigned char": {
            "kind": "char",
            "size": 1,
            "signed": false,
            "endian": "little"
        },
        "pointer": {
            "kind": "int",
            "size": 8,
            "signed": false,
            "endian": "little"
        },
        "unsigned int": {
            "kind": "int",
            "size": 4,
            "signed": false,
            "endian": "little"
        },
        "unsigned short": {
            "kind": "int",
            "size": 2,
            "signed": false,
            "endian": "little"
        },
        "unsigned be short": {
            "kind": "int",
            "size": 2,
            "signed": false,
            "endian": "big"
        },
        "long long": {
          "endian": "little",
          "kind": "int",
          "signed": true,
          "size": 8
        },
        "long": {
            "kind": "int",
            "size": 4,
            "signed": false,
            "endian": "little"
        }
    },
  "symbols": {},
  "user_types": {
      "_UDP_ENDPOINT": {
        "fields": {
            "Owner": {
                "offset": 40,
                "type": {
                    "kind": "pointer",
                    "subtype": {
                        "kind": "struct",
                        "name": "nt_symbols!_EPROCESS"
                    }

                }
            },
            "CreateTime": {
                "offset": 88,
                "type": {
                    "kind": "union",
                    "name": "_LARGE_INTEGER"
                }
            },
            "LocalAddr": {
                "offset": 128,
                "type":{
                    "kind": "pointer",
                    "subtype": {
                        "kind": "struct",
                        "name": "_LOCAL_ADDRESS_WIN10_UDP"
                    }
                }
            },
            "InetAF": {
                "offset": 32,
                "type":{
                    "kind": "pointer",
                    "subtype": {
                        "kind": "struct",
                        "name": "_INETAF"
                    }

                }
            },
            "Port": {
                "offset": 120,
                "type": {
                    "kind": "base",
                    "name": "unsigned be short"
                }
            }
        },
        "kind": "struct",
        "size": 132
    },
    "_TCP_LISTENER": {
        "fields": {
            "Owner": {
                "offset": 48,
                "type": {
                    "kind": "pointer",
                    "subtype": {
                        "kind": "struct",
                        "name": "nt_symbols!_EPROCESS"
                    }

                }
            },
            "CreateTime": {
                "offset": 64,
                "type": {
                    "kind": "union",
                    "name": "_LARGE_INTEGER"
                }
            },
            "LocalAddr": {
                "offset": 96,
                "type":{
                    "kind": "pointer",
                    "subtype": {
                        "kind": "struct",
                        "name": "_LOCAL_ADDRESS"
                    }

                }
            },
            "InetAF": {
                "offset": 40,
                "type":{
                    "kind": "pointer",
                    "subtype": {
                        "kind": "struct",
                        "name": "_INETAF"
                    }

                }
            },
            "Port": {
                "offset": 114,
                "type": {
                    "kind": "base",
                    "name": "unsigned be short"
                }
            }
        },
        "kind": "struct",
        "size": 116
    },
    "_TCP_ENDPOINT": {
        "fields": {
            "Owner": {
                "offset": 600,
                "type": {
                    "kind": "pointer",
                    "subtype": {
                        "kind": "struct",
                        "name": "nt_symbols!_EPROCESS"
                    }
                }
            },
            "CreateTime": {
                "offset": 616,
                "type": {
                    "kind": "union",
                    "name": "_LARGE_INTEGER"
                }
            },
            "AddrInfo": {
                "offset": 24,
                "type":{
                    "kind": "pointer",
                    "subtype": {
                        "kind": "struct",
                        "name": "_ADDRINFO"
                    }
                }
            },
            "InetAF": {
                "offset": 16,
                "type":{
                    "kind": "pointer",
                    "subtype": {
                        "kind": "struct",
                        "name": "_INETAF"
                    }

                }
            },
            "LocalPort": {
                "offset": 112,
                "type": {
                    "kind": "base",
                    "name": "unsigned be short"
                }
            },
            "RemotePort": {
                "offset": 114,
                "type": {
                    "kind": "base",
                    "name": "unsigned be short"
                }
            },
            "State": {
                "offset": 108,
                "type": {
                    "kind": "enum",
                    "name": "TCPStateEnum"
                }
            }
        },
        "kind": "struct",
        "size": 624
    },
    "_LOCAL_ADDRESS": {
        "fields": {
            "pData": {
                "offset": 16,
                "type": {
                    "kind": "pointer",
                    "subtype": {
                        "kind": "pointer",
                        "subtype": {
                            "kind": "struct",
                            "name": "_IN_ADDR"
                        }
                    }
                }
            }
        },
        "kind": "struct",
        "size": 20
    },
    "_LOCAL_ADDRESS_WIN10_UDP": {
        "fields": {
            "pData": {
                "offset": 0,
                "type": {
                    "kind": "pointer",
                    "subtype": {
                        "kind": "struct",
                        "name": "_IN_ADDR"
                    }
                }
            }
        },
        "kind": "struct",
        "size": 4
    },
    "_ADDRINFO": {
        "fields": {
            "Local": {
                "offset": 0,
                "type": {
                    "kind": "pointer",
                    "subtype": {
                        "kind": "struct",
                        "name": "_LOCAL_ADDRESS"
                    }
                }
            },
            "Remote": {
                "offset": 16,
                "type": {
                    "kind": "pointer",
                    "subtype": {
                        "kind": "struct",
                        "name": "_IN_ADDR"
                    }
                }
            }
        },
        "kind": "struct",
        "size": 4
    },
    "_IN_ADDR": {
        "fields": {
            "addr4": {
                "offset": 0,
                "type": {
                    "count": 4,
                    "subtype": {
                        "kind": "base",
                        "name": "unsigned char"
                    },
                    "kind": "array"
                }
            },
            "addr6": {
                "offset": 0,
                "type": {
                    "count": 16,
                    "subtype": {
                        "kind": "base",
                        "name": "unsigned char"
                    },
                    "kind": "array"
                }
            }
        },
        "kind": "struct",
        "size": 6
    },
    "_INETAF": {
        "fields": {
            "AddressFamily": {
                "offset": 24,
                "type": {
                    "kind": "base",
                    "name": "unsigned short"
                }
            }
        },
        "kind": "struct",
        "size": 26
    },
    "_LARGE_INTEGER": {
      "fields": {
        "HighPart": {
          "offset": 4,
          "type": {
            "kind": "base",
            "name": "long"
          }
        },
        "LowPart": {
          "offset": 0,
          "type": {
            "kind": "base",
            "name": "unsigned long"
          }
        },
        "QuadPart": {
          "offset": 0,
          "type": {
            "kind": "base",
            "name": "long long"
          }
        },
        "u": {
          "offset": 0,
          "type": {
            "kind": "struct",
            "name": "__unnamed_2"
          }
        }
      },
      "kind": "union",
      "size": 8
    }
  },
  "enums": {
    "TCPStateEnum": {
        "base": "long",
        "constants": {
            "CLOSED": 0,
            "LISTENING": 1,
            "SYN_SENT": 2,
            "SYN_RCVD": 3,
            "ESTABLISHED": 4,
            "FIN_WAIT1": 5,
            "FIN_WAIT2": 6,
            "CLOSE_WAIT": 7,
            "CLOSING": 8,
            "LAST_ACK": 9,
            "TIME_WAIT": 12,
            "DELETE_TCB": 13
        },
        "size": 4
    }
  },
  "metadata": {
    "producer": {
      "version": "0.0.1",
      "name": "japhlange-by-hand",
      "datetime": "2020-06-12T11:00:00"
    },
    "format": "6.0.0"
  }
}

=== DFIRKuiper/Kuiper/kuiper/app/parsers/vol_Parser/volatility/framework/symbols/linux/bash64.json
{
    "symbols": {}, 
    "enums": {}, 
    "base_types": {
        "unsigned char": {
            "kind": "char", 
            "size": 1, 
            "signed": false, 
            "endian": "little"
        }, 
        "pointer": {
            "kind": "int", 
            "size": 8, 
            "signed": false, 
            "endian": "little"
        }
    }, 
    "user_types": {
        "hist_entry": {
            "fields": {
                "timestamp": {
                    "type": {
                        "subtype": {
                            "count": 1024, 
                            "subtype": {
                                "kind": "base", 
                                "name": "unsigned char"
                            }, 
                            "kind": "array"
                        }, 
                        "kind": "pointer"
                    }, 
                    "offset": 8
                }, 
                "line": {
                    "type": {
                        "subtype": {
                            "count": 1024, 
                            "subtype": {
                                "kind": "base", 
                                "name": "unsigned char"
                            }, 
                            "kind": "array"
                        }, 
                        "kind": "pointer"
                    }, 
                    "offset": 0
                }, 
                "data": {
                    "type": {
                        "subtype": {
                            "kind": "struct", 
                            "name": "void"
                        }, 
                        "kind": "pointer"
                    }, 
                    "offset": 16
                }
            }, 
            "kind": "struct", 
            "size": 24
        }
    }, 
    "metadata": {
        "producer": {
            "version": "0.0.1", 
            "name": "/mnt/hgfs/volshared/vtypes_to_json.py", 
            "datetime": "2018-12-03T09:55:34.880766"
        }, 
        "format": "4.1.0"
    }
}

=== DFIRKuiper/Kuiper/kuiper/app/parsers/vol_Parser/volatility/framework/symbols/windows/bigpools-vista-x64.json
{
  "metadata": {
    "producer": {
      "version": "0.0.1",
      "name": "dlassalle-by-hand",
      "datetime": "2020-04-30T14:30:00.000000"
    },
    "format": "6.2.0"
  },
  "user_types": {
    "_POOL_TRACKER_BIG_PAGES": {
      "fields": {
        "Va": {
          "offset": 0,
          "type": {
            "kind": "base",
            "name": "unsigned long long"
          }
        },
        "Key": {
          "offset": 8,
          "type": {
            "kind": "base",
            "name": "unsigned long"
          }
        },
        "PoolType": {
          "offset": 12,
          "type": {
            "kind": "base",
            "name": "unsigned long"
          }
        },
        "NumberOfBytes": {
          "offset": 16,
          "type": {
            "kind": "base",
            "name": "unsigned long long"
          }
        }
      },
      "kind": "struct",
      "size": 24
    }
  },
  "symbols": {
  },
  "enums": {
    "_POOL_TYPE": {
      "base": "unsigned long",
      "constants": {
        "NonPagedPoolBase": 0,
        "PagedPool": 1,
        "NonPagedPoolBaseMustSucceed": 2,
        "DontUseThisType": 3,
        "NonPagedPoolBaseCacheAligned": 4,
        "PagedPoolCacheAligned": 5,
        "NonPagedPoolBaseCacheAlignedMustS": 6,
        "MaxPoolType": 7,
        "NonPagedPoolMustSucceedSession": 34,
        "DontUseThisTypeSession": 35,
        "NonPagedPoolSession": 32,
        "NonPagedPoolNx": 512,
        "NonPagedPoolSessionNx": 544,
        "NonPagedPoolNxCacheAligned": 516,
        "PagedPoolSession": 33,
        "NonPagedPoolCacheAlignedMustSSession": 38,
        "PagedPoolCacheAlignedSession": 37,
        "NonPagedPoolCacheAlignedSession": 36
      },
      "size": 4
    }
  },
  "base_types": {
    "unsigned long long": {
      "endian": "little",
      "kind": "int",
      "signed": false,
      "size": 8
    },
    "unsigned long": {
      "endian": "little",
      "kind": "int",
      "signed": false,
      "size": 4
    }
  }
}

=== DFIRKuiper/Kuiper/kuiper/app/parsers/vol_Parser/volatility/framework/symbols/windows/poolheader-x64-win7.json
{
  "metadata": {
    "producer": {
      "version": "0.1.5",
      "name": "mhl-by-hand",
      "datetime": "2018-10-03T16:53:00.478000"
    },
    "format": "4.0.0"
  },
  "user_types": {
    "_POOL_HEADER": {
      "fields": {
        "BlockSize": {
          "offset": 0,
          "type": {
            "bit_length": 8,
            "bit_position": 16,
            "kind": "bitfield",
            "type": {
              "kind": "base",
              "name": "unsigned long"
            }
          }
        },
        "PoolIndex": {
          "offset": 0,
          "type": {
            "bit_length": 8,
            "bit_position": 8,
            "kind": "bitfield",
            "type": {
              "kind": "base",
              "name": "unsigned long"
            }
          }
        },
        "PoolTag": {
          "offset": 4,
          "type": {
            "kind": "base",
            "name": "unsigned long"
          }
        },
        "PoolType": {
          "offset": 0,
          "type": {
            "bit_length": 8,
            "bit_position": 24,
            "kind": "bitfield",
            "type": {
              "kind": "base",
              "name": "unsigned long"
            }
          }
        }
      },
      "kind": "struct",
      "size": 16
    }
  },
  "symbols": {
  },
  "enums": {
  },
  "base_types": {
    "unsigned long": {
      "endian": "little",
      "kind": "int",
      "signed": false,
      "size": 4
    },
    "int": {
      "endian": "little",
      "kind": "int",
      "signed": true,
      "size": 4
    }
  }
}
