=== DFIRKuiper/Kuiper/kuiper/app/parsers/vol_Parser/volatility/schemas/schema-6.1.0.json
{
  "$schema": "http://json-schema.org/schema#",
  "id": "http://volatilityfoundation.org/intermediate-format/schema",
  "title": "Symbol Container",
  "type": "object",
  "definitions": {
    "metadata_producer": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "version": {
          "type": "string"
        },
        "datetime": {
          "type": "string",
          "format": "date-time"
        }
      }
    },
    "metadata_windows_pe": {
      "type": "object",
      "properties": {
        "major": {
          "type": "integer"
        },
        "minor": {
          "type": "integer"
        },
        "revision": {
          "type": "integer"
        },
        "build": {
          "type": "integer"
        }
      },
      "additionalProperties": false,
      "required": [
        "major",
        "minor",
        "revision"
      ]
    },
    "metadata_windows_pdb": {
      "type": "object",
      "properties": {
        "GUID": {
          "type": "string"
        },
        "age": {
          "type": "integer"
        },
        "database": {
          "type": "string"
        },
        "machine_type": {
          "type": "integer"
        }
      },
      "additionalProperties": false,
      "required": [
        "GUID",
        "age",
        "database",
        "machine_type"
      ]
    },
    "metadata_windows": {
      "type": "object",
      "properties": {
        "pe": {
          "$ref": "#/definitions/metadata_windows_pe"
        },
        "pdb": {
          "$ref": "#/definitions/metadata_windows_pdb"
        }
      },
      "additionalProperties": false
    },
    "metadata_linux": {
      "type": "object",
      "$comment": "Reserved for future use"
    },
    "metadata_format": {
      "type": "string",
      "pattern": "^6.[0-9]+.[0-9]+$"
    },
    "metadata_source": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string"
        }
      }
    },
    "element_metadata": {
      "type": "object",
      "oneOf": [
        {
          "properties": {
            "format": {
              "$ref": "#/definitions/metadata_format"
            },
            "producer": {
              "$ref": "#/definitions/metadata_producer"
            }
          },
          "required": [
            "format"
          ],
          "additionalProperties": false
        },
        {
          "properties": {
            "format": {
              "$ref": "#/definitions/metadata_format"
            },
            "producer": {
              "$ref": "#/definitions/metadata_producer"
            },
            "windows": {
              "$ref": "#/definitions/metadata_windows"
            }
          },
          "required": [
            "format",
            "windows"
          ],
          "additionalProperties": false
        },
        {
          "properties": {
            "format": {
              "$ref": "#/definitions/metadata_format"
            },
            "producer": {
              "$ref": "#/definitions/metadata_producer"
            },
            "linux": {
              "$ref": "#/definitions/metadata_linux"
            }
          },
          "required": [
            "format",
            "linux"
          ],
          "additionalProperties": false
        }
      ]
    },
    "element_enum": {
      "properties": {
        "size": {
          "type": "integer"
        },
        "base": {
          "type": "string"
        },
        "constants": {
          "type": "object",
          "additionalProperties": {
            "type": "integer"
          }
        }
      },
      "required": [
        "size",
        "base",
        "constants"
      ],
      "additionalProperties": false
    },
    "element_symbol": {
      "properties": {
        "address": {
          "type": "number"
        },
        "linkage_name": {
          "type": "string"
        },
        "type": {
          "$ref": "#/definitions/type_descriptor"
        },
        "constant_data": {
          "type": "string",
          "media": {
            "binaryEncoding": "base64",
            "readOnly": true
          }
        }
      },
      "required": [
        "address"
      ],
      "additionalProperties": false
    },
    "element_base_type": {
      "properties": {
        "size": {
          "type": "integer"
        },
        "signed": {
          "type": "boolean"
        },
        "kind": {
          "type": "string",
          "pattern": "^(void|int|float|char|bool)$"
        },
        "endian": {
          "type": "string",
          "pattern": "^(little|big)$"
        }
      },
      "required": [
        "size",
        "kind",
        "signed",
        "endian"
      ],
      "additionalProperties": false
    },
    "element_user_type": {
      "properties": {
        "kind": {
          "type": "string",
          "pattern": "^(struct|union|class)$"
        },
        "size": {
          "type": "integer"
        },
        "fields": {
          "type": "object",
          "additionalProperties": {
            "$ref": "#/definitions/field"
          }
        }
      },
      "required": [
        "kind",
        "size",
        "fields"
      ],
      "additionalProperties": false
    },
    "field": {
      "properties": {
        "type": {
          "$ref": "#/definitions/type_descriptor"
        },
        "offset": {
          "type": "integer"
        }
      },
      "required": [
        "type",
        "offset"
      ],
      "additionalProperties": false
    },
    "type_descriptor": {
      "oneOf": [
        {
          "$ref": "#/definitions/type_pointer"
        },
        {
          "$ref": "#/definitions/type_base"
        },
        {
          "$ref": "#/definitions/type_array"
        },
        {
          "$ref": "#/definitions/type_struct"
        },
        {
          "$ref": "#/definitions/type_enum"
        },
        {
          "$ref": "#/definitions/type_function"
        },
        {
          "$ref": "#/definitions/type_bitfield"
        }
      ]
    },
    "type_pointer": {
      "properties": {
        "kind": {
          "type": "string",
          "pattern": "^pointer$"
        },
        "base": {
          "type": "string"
        },
        "subtype": {
          "$ref": "#/definitions/type_descriptor"
        }
      },
      "required": [
        "kind",
        "subtype"
      ],
      "additionalProperties": false
    },
    "type_base": {
      "properties": {
        "kind": {
          "type": "string",
          "pattern": "^base$"
        },
        "name": {
          "type": "string"
        }
      },
      "required": [
        "kind",
        "name"
      ],
      "additionalProperties": false
    },
    "type_array": {
      "properties": {
        "kind": {
          "type": "string",
          "pattern": "^array$"
        },
        "subtype": {
          "$ref": "#/definitions/type_descriptor"
        },
        "count": {
          "type": "integer"
        }
      },
      "required": [
        "kind",
        "subtype",
        "count"
      ],
      "additionalProperties": false
    },
    "type_struct": {
      "properties": {
        "kind": {
          "type": "string",
          "pattern": "^(struct|class|union)$"
        },
        "name": {
          "type": "string"
        }
      },
      "required": [
        "kind",
        "name"
      ],
      "additionalProperties": false
    },
    "type_enum": {
      "properties": {
        "kind": {
          "type": "string",
          "pattern": "^enum$"
        },
        "name": {
          "type": "string"
        }
      },
      "required": [
        "kind",
        "name"
      ],
      "additionalProperties": false
    },
    "type_function": {
      "properties": {
        "kind": {
          "type": "string",
          "pattern": "^function$"
        }
      },
      "required": [
        "kind"
      ],
      "additionalProperties": false
    },
    "type_bitfield": {
      "properties": {
        "kind": {
          "type": "string",
          "pattern": "^bitfield$"
        },
        "bit_position": {
          "type": "integer"
        },
        "bit_length": {
          "type": "integer"
        },
        "type": {
          "oneOf": [
            {
              "$ref": "#/definitions/type_base"
            },
            {
              "$ref": "#/definitions/type_enum"
            }
          ]
        }
      },
      "required": [
        "kind",
        "bit_position",
        "bit_length",
        "type"
      ],
      "additionalProperties": false
    }
  },
  "properties": {
    "metadata": {
      "$ref": "#/definitions/element_metadata"
    },
    "base_types": {
      "additionalProperties": {
        "$ref": "#/definitions/element_base_type"
      }
    },
    "user_types": {
      "additionalProperties": {
        "$ref": "#/definitions/element_user_type"
      }
    },
    "enums": {
      "additionalProperties": {
        "$ref": "#/definitions/element_enum"
      }
    },
    "symbols": {
      "additionalProperties": {
        "$ref": "#/definitions/element_symbol"
      }
    }
  },
  "required": [
    "metadata",
    "base_types",
    "user_types",
    "enums",
    "symbols"
  ],
  "additionalProperties": false
}

=== DFIRKuiper/Kuiper/kuiper/app/parsers/vol_Parser/volatility/framework/symbols/windows/registry.json
{
  "symbols": {
  },
  "user_types": {
    "__unnamed_114": {
      "fields": {
        "Next": {
          "offset": 0,
          "type": {
            "kind": "base",
            "name": "unsigned long"
          }
        },
        "UserData": {
          "offset": 0,
          "type": {
            "kind": "base",
            "name": "unsigned long"
          }
        }
      },
      "kind": "union",
      "size": 4
    },
    "__unnamed_115": {
      "fields": {
        "Last": {
          "offset": 0,
          "type": {
            "kind": "base",
            "name": "unsigned long"
          }
        },
        "u": {
          "offset": 4,
          "type": {
            "kind": "union",
            "name": "__unnamed_114"
          }
        }
      },
      "kind": "struct",
      "size": 8
    },
    "__unnamed_116": {
      "fields": {
        "u": {
          "offset": 0,
          "type": {
            "kind": "union",
            "name": "__unnamed_114"
          }
        }
      },
      "kind": "struct",
      "size": 4
    },
    "__unnamed_117": {
      "fields": {
        "NewCell": {
          "offset": 0,
          "type": {
            "kind": "struct",
            "name": "__unnamed_116"
          }
        },
        "OldCell": {
          "offset": 0,
          "type": {
            "kind": "struct",
            "name": "__unnamed_115"
          }
        }
      },
      "kind": "union",
      "size": 8
    },
    "_HBIN": {
      "fields": {
        "FileOffset": {
          "offset": 4,
          "type": {
            "kind": "base",
            "name": "unsigned long"
          }
        },
        "Reserved1": {
          "offset": 12,
          "type": {
            "count": 2,
            "kind": "array",
            "subtype": {
              "kind": "base",
              "name": "unsigned long"
            }
          }
        },
        "Signature": {
          "offset": 0,
          "type": {
            "kind": "base",
            "name": "unsigned long"
          }
        },
        "Size": {
          "offset": 8,
          "type": {
            "kind": "base",
            "name": "unsigned long"
          }
        },
        "Spare": {
          "offset": 28,
          "type": {
            "kind": "base",
            "name": "unsigned long"
          }
        },
        "TimeStamp": {
          "offset": 20,
          "type": {
            "kind": "union",
            "name": "_LARGE_INTEGER"
          }
        }
      },
      "kind": "struct",
      "size": 32
    },
    "_HCELL": {
      "fields": {
        "Size": {
          "offset": 0,
          "type": {
            "kind": "base",
            "name": "long"
          }
        },
        "u": {
          "offset": 4,
          "type": {
            "kind": "union",
            "name": "__unnamed_117"
          }
        }
      },
      "kind": "struct",
      "size": 12
    },
    "_VOL_USERASSIST_TYPES_XP": {
      "fields": {
        "ID": {
          "offset": 0,
          "type": {
            "kind": "base",
            "name": "unsigned long"
          }
        },
        "CountStartingAtFive": {
          "offset": 4,
          "type": {
            "kind": "base",
            "name": "unsigned long"
          }
        },
        "LastUpdated": {
          "offset": 8,
          "type": {
            "kind": "union",
            "name": "_LARGE_INTEGER"
          }
        }
      },
      "kind": "struct",
      "size": 16
    },
    "_VOL_USERASSIST_TYPES_7": {
      "fields": {
        "Count": {
          "offset": 4,
          "type": {
            "kind": "base",
            "name": "unsigned long"
          }
        },
        "FocusCount": {
          "offset": 8,
          "type": {
            "kind": "base",
            "name": "unsigned long"
          }
        },
        "FocusTime": {
          "offset": 12,
          "type": {
            "kind": "base",
            "name": "unsigned long"
          }
        },
        "LastUpdated": {
          "offset": 60,
          "type": {
            "kind": "union",
            "name": "_LARGE_INTEGER"
          }
        }
      },
      "kind": "struct",
      "size": 72
    },
    "_LARGE_INTEGER": {
      "fields": {
        "HighPart": {
          "offset": 4,
          "type": {
            "kind": "base",
            "name": "long"
          }
        },
        "LowPart": {
          "offset": 0,
          "type": {
            "kind": "base",
            "name": "unsigned long"
          }
        },
        "QuadPart": {
          "offset": 0,
          "type": {
            "kind": "base",
            "name": "long long"
          }
        },
        "u": {
          "offset": 0,
          "type": {
            "kind": "struct",
            "name": "__unnamed_2"
          }
        }
      },
      "kind": "union",
      "size": 8
    },
    "__unnamed_2": {
      "fields": {
        "HighPart": {
          "offset": 4,
          "type": {
            "kind": "base",
            "name": "long"
          }
        },
        "LowPart": {
          "offset": 0,
          "type": {
            "kind": "base",
            "name": "unsigned long"
          }
        }
      },
      "kind": "struct",
      "size": 8
    }
  },
  "enums": {
  },
  "base_types": {
    "unsigned char": {
      "endian": "little",
      "kind": "char",
      "signed": false,
      "size": 1
    },
    "unsigned short": {
      "endian": "little",
      "kind": "int",
      "signed": false,
      "size": 2
    },
    "long": {
      "endian": "little",
      "kind": "int",
      "signed": true,
      "size": 4
    },
    "char": {
      "endian": "little",
      "kind": "char",
      "signed": true,
      "size": 1
    },
    "unsigned long": {
      "endian": "little",
      "kind": "int",
      "signed": false,
      "size": 4
    },
    "long long": {
      "endian": "little",
      "kind": "int",
      "signed": true,
      "size": 8
    },
    "unsigned long long": {
      "endian": "little",
      "kind": "int",
      "signed": false,
      "size": 8
    }
  },
  "metadata": {
    "producer": {
      "version": "0.0.1",
      "name": "ikelos-by-hand",
      "datetime": "2017-09-04T22:45:22"
    },
    "format": "4.0.0"
  }
}

=== DFIRKuiper/Kuiper/kuiper/app/parsers/vol_Parser/volatility/framework/symbols/windows/bigpools-x64.json
{
  "metadata": {
    "producer": {
      "version": "0.0.1",
      "name": "dlassalle-by-hand",
      "datetime": "2020-04-30T14:30:00.000000"
    },
    "format": "6.2.0"
  },
  "user_types": {
    "_POOL_TRACKER_BIG_PAGES": {
      "fields": {
        "Va": {
          "offset": 0,
          "type": {
            "kind": "base",
            "name": "unsigned long long"
          }
        },
        "Key": {
          "offset": 8,
          "type": {
            "kind": "base",
            "name": "unsigned long"
          }
        }
      },
      "kind": "struct",
      "size": 12
    }
  },
  "symbols": {
  },
  "enums": {
    "_POOL_TYPE": {
      "base": "unsigned long",
      "constants": {
        "NonPagedPool": 0,
        "PagedPool": 1,
        "NonPagedPoolMustSucceed": 2,
        "DontUseThisType": 3,
        "NonPagedPoolCacheAligned": 4,
        "PagedPoolAligned": 5,
        "NonPagedPoolCacheAlignedMustS": 6,
        "MaxPoolType": 7,
        "NonPagedPoolMustSucceedSession": 34,
        "DontUseThisTypeSession": 35,
        "NonPagedPoolSession": 32,
        "PagedPoolSession": 33,
        "NonPagedPoolCacheAlignedMustSSession": 38,
        "PagedPoolCacheAlignedSession": 37,
        "NonPagedPoolCacheAlignedSession": 36
      },
      "size": 4
    }
  },
  "base_types": {
        "unsigned long long": {
      "endian": "little",
      "kind": "int",
      "signed": false,
      "size": 8
    },
    "unsigned long": {
      "endian": "little",
      "kind": "int",
      "signed": false,
      "size": 4
    }
  }
}

=== DFIRKuiper/Kuiper/kuiper/app/parsers/vol_Parser/volatility/framework/symbols/windows/crash.json
{
  "symbols": {
  },
  "user_types": {
    "_DUMP_HEADER": {
      "fields": {
        "Signature": {
          "offset": 0,
          "type": {
            "count": 4,
            "kind": "array",
            "subtype": {
              "kind": "base",
              "name": "unsigned char"
            }
          }
        },
        "ValidDump": {
          "offset": 4,
          "type": {
            "count": 4,
            "kind": "array",
            "subtype": {
              "kind": "base",
              "name": "unsigned char"
            }
          }
        },
        "MajorVersion": {
          "offset": 8,
          "type": {
            "kind": "base",
            "name": "unsigned long"
          }
        },
        "MinorVersion": {
          "offset": 12,
          "type": {
            "kind": "base",
            "name": "unsigned long"
          }
        },
        "DirectoryTableBase": {
          "offset": 16,
          "type": {
            "kind": "base",
            "name": "unsigned long"
          }
        },
        "PfnDataBase": {
          "offset": 20,
          "type": {
            "kind": "base",
            "name": "unsigned long"
          }
        },
        "PsLoadedModuleList": {
          "offset": 24,
          "type": {
            "kind": "base",
            "name": "unsigned long"
          }
        },
        "PsActiveProcessHead": {
          "offset": 28,
          "type": {
            "kind": "base",
            "name": "unsigned long"
          }
        },
        "MachineImageType": {
          "offset": 32,
          "type": {
            "kind": "base",
            "name": "unsigned long"
          }
        },
        "NumberProcessors": {
          "offset": 36,
          "type": {
            "kind": "base",
            "name": "unsigned long"
          }
        },
        "BugCheckCode": {
          "offset": 40,
          "type": {
            "kind": "base",
            "name": "unsigned long"
          }
        },
        "BugCheckCodeParameter": {
          "offset": 44,
          "type": {
            "count": 4,
            "kind": "array",
            "subtype": {
              "kind": "base",
              "name": "unsigned long"
            }
          }
        },
        "VersionUser": {
          "offset": 60,
          "type": {
            "count": 32,
            "kind": "array",
            "subtype": {
              "kind": "base",
              "name": "unsigned char"
            }
          }
        },
        "PaeEnabled": {
          "offset": 92,
          "type": {
            "kind": "base",
            "name": "unsigned char"
          }
        },
        "KdSecondaryVersion": {
          "offset": 93,
          "type": {
            "kind": "base",
            "name": "unsigned char"
          }
        },
        "VersionUser2": {
          "offset": 94,
          "type": {
            "count": 2,
            "kind": "array",
            "subtype": {
              "kind": "base",
              "name": "unsigned char"
            }
          }
        },
        "KdDebuggerDataBlock": {
          "offset": 96,
          "type": {
            "kind": "base",
            "name": "unsigned long"
          }
        },
        "PhysicalMemoryBlockBuffer": {
          "offset": 100,
          "type": {
            "kind": "struct",
            "name": "_PHYSICAL_MEMORY_DESCRIPTOR"
          }
        },
        "ContextRecord": {
          "offset": 800,
          "type": {
            "count": 1200,
            "kind": "array",
            "subtype": {
              "kind": "base",
              "name": "unsigned char"
            }
          }
        },
        "Exception": {
          "offset": 2000,
          "type": {
            "kind": "struct",
            "name": "_EXCEPTION_RECORD32"
          }
        },
        "Comment": {
          "offset": 2080,
          "type": {
            "count": 128,
            "kind": "array",
            "subtype": {
              "kind": "base",
              "name": "unsigned char"
            }
          }
        },
        "DumpType": {
          "offset": 3976,
          "type": {
            "kind": "base",
            "name": "unsigned long"
          }
        },
        "MiniDumpFields": {
          "offset": 3980,
          "type": {
            "kind": "base",
            "name": "unsigned long"
          }
        },
        "SecondaryDataState": {
          "offset": 3984,
          "type": {
            "kind": "base",
            "name": "unsigned long"
          }
        },
        "ProductType": {
          "offset": 3988,
          "type": {
            "kind": "base",
            "name": "unsigned long"
          }
        },
        "SuiteMask": {
          "offset": 3992,
          "type": {
            "kind": "base",
            "name": "unsigned long"
          }
        },
        "WriterStatus": {
          "offset": 3996,
          "type": {
            "kind": "base",
            "name": "unsigned long"
          }
        },
        "RequiredDumpSpace": {
          "offset": 4000,
          "type": {
            "kind": "base",
            "name": "unsigned long long"
          }
        },
        "SystemUpTime": {
          "offset": 4024,
          "type": {
            "kind": "base",
            "name": "unsigned long long"
          }
        },
        "SystemTime": {
          "offset": 4032,
          "type": {
            "kind": "base",
            "name": "unsigned long long"
          }
        },
        "reserved3": {
          "offset": 4040,
          "type": {
            "count": 56,
            "kind": "array",
            "subtype": {
              "kind": "base",
              "name": "unsigned char"
            }
          }
        }
      },
      "kind": "struct",
      "size": 4096
    },
    "_EXCEPTION_RECORD32": {
      "fields": {
        "ExceptionCode": {
          "offset": 0,
          "type": {
            "kind": "base",
            "name": "long"
          }
        },
        "ExceptionFlags": {
          "offset": 4,
          "type": {
            "kind": "base",
            "name": "unsigned long"
          }
        },
        "ExceptionRecord": {
          "offset": 8,
          "type": {
            "kind": "base",
            "name": "unsigned long"
          }
        },
        "ExceptionAddress": {
          "offset": 12,
          "type": {
            "kind": "base",
            "name": "unsigned long"
          }
        },
        "NumberParameters": {
          "offset": 16,
          "type": {
            "kind": "base",
            "name": "unsigned long"
          }
        },
        "ExceptionInformation": {
          "offset": 20,
          "type": {
            "count": 15,
            "kind": "array",
            "subtype": {
              "kind": "base",
              "name": "unsigned long"
            }
          }
        }
      },
      "kind": "struct",
      "size": 80
    },
    "_PHYSICAL_MEMORY_DESCRIPTOR": {
      "fields": {
        "NumberOfPages": {
          "offset": 4,
          "type": {
            "kind": "base",
            "name": "unsigned long"
          }
        },
        "NumberOfRuns": {
          "offset": 0,
          "type": {
            "kind": "base",
            "name": "unsigned long"
          }
        },
        "Run": {
          "offset": 8,
          "type": {
            "count": 1,
            "kind": "array",
            "subtype": {
              "kind": "struct",
              "name": "_PHYSICAL_MEMORY_RUN"
            }
          }
        }
      },
      "kind": "struct",
      "size": 16
    },
    "_PHYSICAL_MEMORY_RUN": {
      "fields": {
        "BasePage": {
          "offset": 0,
          "type": {
            "kind": "base",
            "name": "unsigned long"
          }
        },
        "PageCount": {
          "offset": 4,
          "type": {
            "kind": "base",
            "name": "unsigned long"
          }
        }
      },
      "kind": "struct",
      "size": 8
    }
  },
  "enums": {
  },
  "base_types": {
    "unsigned char": {
      "endian": "little",
      "kind": "char",
      "signed": false,
      "size": 1
    },
    "unsigned short": {
      "endian": "little",
      "kind": "int",
      "signed": false,
      "size": 2
    },
    "long": {
      "endian": "little",
      "kind": "int",
      "signed": true,
      "size": 4
    },
    "char": {
      "endian": "little",
      "kind": "char",
      "signed": true,
      "size": 1
    },
    "unsigned long": {
      "endian": "little",
      "kind": "int",
      "signed": false,
      "size": 4
    },
    "long long": {
      "endian": "little",
      "kind": "int",
      "signed": true,
      "size": 8
    },
    "unsigned long long": {
      "endian": "little",
      "kind": "int",
      "signed": false,
      "size": 8
    }
  },
  "metadata": {
    "producer": {
      "version": "0.0.2",
      "name": "awalters-by-hand",
      "datetime": "2018-05-01T16:30:00"
    },
    "format": "4.1.0"
  }
}
