=== DFIRKuiper/Kuiper/kuiper/app/parsers/vol_Parser/volatility/schemas/schema-6.1.0.json
{
  "$schema": "http://json-schema.org/schema#",
  "id": "http://volatilityfoundation.org/intermediate-format/schema",
  "title": "Symbol Container",
  "type": "object",
  "definitions": {
    "metadata_producer": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "version": {
          "type": "string"
        },
        "datetime": {
          "type": "string",
          "format": "date-time"
        }
      }
    },
    "metadata_windows_pe": {
      "type": "object",
      "properties": {
        "major": {
          "type": "integer"
        },
        "minor": {
          "type": "integer"
        },
        "revision": {
          "type": "integer"
        },
        "build": {
          "type": "integer"
        }
      },
      "additionalProperties": false,
      "required": [
        "major",
        "minor",
        "revision"
      ]
    },
    "metadata_windows_pdb": {
      "type": "object",
      "properties": {
        "GUID": {
          "type": "string"
        },
        "age": {
          "type": "integer"
        },
        "database": {
          "type": "string"
        },
        "machine_type": {
          "type": "integer"
        }
      },
      "additionalProperties": false,
      "required": [
        "GUID",
        "age",
        "database",
        "machine_type"
      ]
    },
    "metadata_windows": {
      "type": "object",
      "properties": {
        "pe": {
          "$ref": "#/definitions/metadata_windows_pe"
        },
        "pdb": {
          "$ref": "#/definitions/metadata_windows_pdb"
        }
      },
      "additionalProperties": false
    },
    "metadata_linux": {
      "type": "object",
      "$comment": "Reserved for future use"
    },
    "metadata_format": {
      "type": "string",
      "pattern": "^6.[0-9]+.[0-9]+$"
    },
    "metadata_source": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string"
        }
      }
    },
    "element_metadata": {
      "type": "object",
      "oneOf": [
        {
          "properties": {
            "format": {
              "$ref": "#/definitions/metadata_format"
            },
            "producer": {
              "$ref": "#/definitions/metadata_producer"
            }
          },
          "required": [
            "format"
          ],
          "additionalProperties": false
        },
        {
          "properties": {
            "format": {
              "$ref": "#/definitions/metadata_format"
            },
            "producer": {
              "$ref": "#/definitions/metadata_producer"
            },
            "windows": {
              "$ref": "#/definitions/metadata_windows"
            }
          },
          "required": [
            "format",
            "windows"
          ],
          "additionalProperties": false
        },
        {
          "properties": {
            "format": {
              "$ref": "#/definitions/metadata_format"
            },
            "producer": {
              "$ref": "#/definitions/metadata_producer"
            },
            "linux": {
              "$ref": "#/definitions/metadata_linux"
            }
          },
          "required": [
            "format",
            "linux"
          ],
          "additionalProperties": false
        }
      ]
    },
    "element_enum": {
      "properties": {
        "size": {
          "type": "integer"
        },
        "base": {
          "type": "string"
        },
        "constants": {
          "type": "object",
          "additionalProperties": {
            "type": "integer"
          }
        }
      },
      "required": [
        "size",
        "base",
        "constants"
      ],
      "additionalProperties": false
    },
    "element_symbol": {
      "properties": {
        "address": {
          "type": "number"
        },
        "linkage_name": {
          "type": "string"
        },
        "type": {
          "$ref": "#/definitions/type_descriptor"
        },
        "constant_data": {
          "type": "string",
          "media": {
            "binaryEncoding": "base64",
            "readOnly": true
          }
        }
      },
      "required": [
        "address"
      ],
      "additionalProperties": false
    },
    "element_base_type": {
      "properties": {
        "size": {
          "type": "integer"
        },
        "signed": {
          "type": "boolean"
        },
        "kind": {
          "type": "string",
          "pattern": "^(void|int|float|char|bool)$"
        },
        "endian": {
          "type": "string",
          "pattern": "^(little|big)$"
        }
      },
      "required": [
        "size",
        "kind",
        "signed",
        "endian"
      ],
      "additionalProperties": false
    },
    "element_user_type": {
      "properties": {
        "kind": {
          "type": "string",
          "pattern": "^(struct|union|class)$"
        },
        "size": {
          "type": "integer"
        },
        "fields": {
          "type": "object",
          "additionalProperties": {
            "$ref": "#/definitions/field"
          }
        }
      },
      "required": [
        "kind",
        "size",
        "fields"
      ],
      "additionalProperties": false
    },
    "field": {
      "properties": {
        "type": {
          "$ref": "#/definitions/type_descriptor"
        },
        "offset": {
          "type": "integer"
        }
      },
      "required": [
        "type",
        "offset"
      ],
      "additionalProperties": false
    },
    "type_descriptor": {
      "oneOf": [
        {
          "$ref": "#/definitions/type_pointer"
        },
        {
          "$ref": "#/definitions/type_base"
        },
        {
          "$ref": "#/definitions/type_array"
        },
        {
          "$ref": "#/definitions/type_struct"
        },
        {
          "$ref": "#/definitions/type_enum"
        },
        {
          "$ref": "#/definitions/type_function"
        },
        {
          "$ref": "#/definitions/type_bitfield"
        }
      ]
    },
    "type_pointer": {
      "properties": {
        "kind": {
          "type": "string",
          "pattern": "^pointer$"
        },
        "base": {
          "type": "string"
        },
        "subtype": {
          "$ref": "#/definitions/type_descriptor"
        }
      },
      "required": [
        "kind",
        "subtype"
      ],
      "additionalProperties": false
    },
    "type_base": {
      "properties": {
        "kind": {
          "type": "string",
          "pattern": "^base$"
        },
        "name": {
          "type": "string"
        }
      },
      "required": [
        "kind",
        "name"
      ],
      "additionalProperties": false
    },
    "type_array": {
      "properties": {
        "kind": {
          "type": "string",
          "pattern": "^array$"
        },
        "subtype": {
          "$ref": "#/definitions/type_descriptor"
        },
        "count": {
          "type": "integer"
        }
      },
      "required": [
        "kind",
        "subtype",
        "count"
      ],
      "additionalProperties": false
    },
    "type_struct": {
      "properties": {
        "kind": {
          "type": "string",
          "pattern": "^(struct|class|union)$"
        },
        "name": {
          "type": "string"
        }
      },
      "required": [
        "kind",
        "name"
      ],
      "additionalProperties": false
    },
    "type_enum": {
      "properties": {
        "kind": {
          "type": "string",
          "pattern": "^enum$"
        },
        "name": {
          "type": "string"
        }
      },
      "required": [
        "kind",
        "name"
      ],
      "additionalProperties": false
    },
    "type_function": {
      "properties": {
        "kind": {
          "type": "string",
          "pattern": "^function$"
        }
      },
      "required": [
        "kind"
      ],
      "additionalProperties": false
    },
    "type_bitfield": {
      "properties": {
        "kind": {
          "type": "string",
          "pattern": "^bitfield$"
        },
        "bit_position": {
          "type": "integer"
        },
        "bit_length": {
          "type": "integer"
        },
        "type": {
          "oneOf": [
            {
              "$ref": "#/definitions/type_base"
            },
            {
              "$ref": "#/definitions/type_enum"
            }
          ]
        }
      },
      "required": [
        "kind",
        "bit_position",
        "bit_length",
        "type"
      ],
      "additionalProperties": false
    }
  },
  "properties": {
    "metadata": {
      "$ref": "#/definitions/element_metadata"
    },
    "base_types": {
      "additionalProperties": {
        "$ref": "#/definitions/element_base_type"
      }
    },
    "user_types": {
      "additionalProperties": {
        "$ref": "#/definitions/element_user_type"
      }
    },
    "enums": {
      "additionalProperties": {
        "$ref": "#/definitions/element_enum"
      }
    },
    "symbols": {
      "additionalProperties": {
        "$ref": "#/definitions/element_symbol"
      }
    }
  },
  "required": [
    "metadata",
    "base_types",
    "user_types",
    "enums",
    "symbols"
  ],
  "additionalProperties": false
}

=== DFIRKuiper/Kuiper/kuiper/app/parsers/vol_Parser/volatility/framework/symbols/windows/callbacks-x64.json
{
    "symbols": {},
    "enums": {},
    "base_types": {
        "unsigned long": {
            "kind": "int",
            "size": 4,
            "signed": false,
            "endian": "little"
        },
        "unsigned char": {
            "kind": "char",
            "size": 1,
            "signed": false,
            "endian": "little"
        },
        "pointer": {
            "kind": "int",
            "size": 8,
            "signed": false,
            "endian": "little"
        },
        "unsigned int": {
            "kind": "int",
            "size": 4,
            "signed": false,
            "endian": "little"
        },
        "unsigned short": {
            "kind": "int",
            "size": 2,
            "signed": false,
            "endian": "little"
        },
        "long": {
            "kind": "int",
            "size": 4,
            "signed": false,
            "endian": "little"
        }
    },
    "user_types": {
        "_GENERIC_CALLBACK": {
            "fields": {
              "Callback": {
                "type": {
                  "kind": "pointer",
                  "subtype": {
                    "kind": "base",
                    "name": "void"
                  }
                },
                "offset": 8
              }
            },
            "kind": "struct",
            "size": 16
        },
        "_KBUGCHECK_CALLBACK_RECORD": {
            "fields": {
                "Entry": {
                    "type": {
                        "kind": "struct",
                        "name": "nt_symbols!_LIST_ENTRY"
                    },
                    "offset": 0
                },
                "CallbackRoutine": {
                    "type": {
                        "kind": "pointer",
                        "subtype": {
                            "kind": "base",
                            "name": "void"
                        }
                    },
                    "offset": 16
                },
                "Component": {
                    "type": {
                        "kind": "pointer",
                        "subtype": {
                            "kind": "base",
                            "name": "unsigned char"
                        }
                    },
                    "offset": 40
                }
            },
            "kind": "struct",
            "size": 64
        },
        "_KBUGCHECK_REASON_CALLBACK_RECORD": {
            "fields": {
                "Entry": {
                    "type": {
                        "kind": "struct",
                        "name": "nt_symbols!_LIST_ENTRY"
                    },
                    "offset": 0
                },
                "CallbackRoutine": {
                    "type": {
                        "kind": "pointer",
                        "subtype": {
                            "kind": "base",
                            "name": "void"
                        }
                    },
                    "offset": 16
                },
                "Component": {
                    "type": {
                        "kind": "pointer",
                        "subtype": {
                            "kind": "base",
                            "name": "unsigned char"
                        }
                    },
                    "offset": 40
                }
            },
            "kind": "struct",
            "size": 64
        },
        "_EX_CALLBACK_ROUTINE_BLOCK": {
            "fields": {
                "Function": {
                    "type": {
                        "kind": "pointer",
                        "subtype": {
                            "kind": "base",
                            "name": "void"
                        }
                    },
                    "offset": 8
                }
            },
            "kind": "struct",
            "size": 64
        }
    },
    "metadata": {
        "producer": {
            "version": "0.0.1",
            "name": "mhl by hand",
            "datetime": "2019-08-27T18:17:16.417006"
        },
        "format": "4.0.0"
    }
}

=== DFIRKuiper/Kuiper/kuiper/app/parsers/vol_Parser/volatility/framework/symbols/windows/poolheader-x64.json
{
  "metadata": {
    "producer": {
      "version": "0.1.5",
      "name": "mhl-by-hand",
      "datetime": "2018-10-03T16:53:00.478000"
    },
    "format": "4.0.0"
  },
  "user_types": {
    "_POOL_HEADER": {
      "fields": {
        "BlockSize": {
          "offset": 2,
          "type": {
            "bit_length": 8,
            "bit_position": 0,
            "kind": "bitfield",
            "type": {
              "kind": "base",
              "name": "unsigned short"
            }
          }
        },
        "PoolIndex": {
          "offset": 0,
          "type": {
            "bit_length": 8,
            "bit_position": 8,
            "kind": "bitfield",
            "type": {
              "kind": "base",
              "name": "unsigned short"
            }
          }
        },
        "PoolTag": {
          "offset": 4,
          "type": {
            "kind": "base",
            "name": "unsigned long"
          }
        },
        "PoolType": {
          "offset": 2,
          "type": {
            "bit_length": 8,
            "bit_position": 8,
            "kind": "bitfield",
            "type": {
              "kind": "base",
              "name": "unsigned short"
            }
          }
        }
      },
      "kind": "struct",
      "size": 16
    }
  },
  "symbols": {
  },
  "enums": {
  },
  "base_types": {
    "unsigned long": {
      "endian": "little",
      "kind": "int",
      "signed": false,
      "size": 4
    },
    "unsigned short": {
      "endian": "little",
      "kind": "int",
      "signed": false,
      "size": 2
    },
    "int": {
      "endian": "little",
      "kind": "int",
      "signed": true,
      "size": 4
    }
  }
}

=== DFIRKuiper/Kuiper/kuiper/app/parsers/vol_Parser/volatility/framework/symbols/windows/services-win10-15063-x64.json
{
    "symbols": {}, 
    "enums": {
        "StateEnum": {
            "base": "long", 
            "constants": {
                "SERVICE_START_PENDING": 2, 
                "SERVICE_STOP_PENDING": 3, 
                "SERVICE_STOPPED": 1, 
                "SERVICE_CONTINUE_PENDING": 5, 
                "SERVICE_PAUSE_PENDING": 6, 
                "SERVICE_PAUSED": 7, 
                "SERVICE_RUNNING": 4
            }, 
            "size": 4
        }, 
        "StartEnum": {
            "base": "long", 
            "constants": {
                "SERVICE_DEMAND_START": 3, 
                "SERVICE_AUTO_START": 2, 
                "SERVICE_BOOT_START": 0, 
                "SERVICE_DISABLED": 4, 
                "SERVICE_SYSTEM_START": 1
            }, 
            "size": 4
        }
    }, 
    "base_types": {
        "unsigned long": {
            "kind": "int", 
            "size": 4, 
            "signed": false, 
            "endian": "little"
        }, 
        "unsigned char": {
            "kind": "char", 
            "size": 1, 
            "signed": false, 
            "endian": "little"
        }, 
        "pointer": {
            "kind": "int", 
            "size": 8, 
            "signed": false, 
            "endian": "little"
        }, 
        "unsigned int": {
            "kind": "int", 
            "size": 4, 
            "signed": false, 
            "endian": "little"
        },
        "unsigned short": {
            "kind": "int",
            "size": 2,
            "signed": false,
            "endian": "little"
        },
        "long": {
            "kind": "int", 
            "size": 4, 
            "signed": false, 
            "endian": "little"
        }
    }, 
    "user_types": {
        "_SERVICE_LIST_ENTRY": {
            "fields": {
                "Flink": {
                    "type": {
                        "kind": "pointer",
                        "subtype": {
                            "kind": "struct",
                            "name": "_SERVICE_LIST_ENTRY"
                        }
                    }, 
                    "offset": 16
                }, 
                "Blink": {
                    "type": {
                        "kind": "pointer",
                        "subtype": {
                            "kind": "struct",
                            "name": "_SERVICE_LIST_ENTRY"
                        }
                    },
                    "offset": 0
                }
            }, 
            "kind": "struct", 
            "size": 16
        }, 
        "_SERVICE_PROCESS": {
            "fields": {
                "BinaryPath": {
                    "type": {
                        "kind": "pointer",
                        "subtype": {
                            "kind": "base",
                            "name": "unsigned short"
                        }
                    },
                    "offset": 24
                }, 
                "ProcessId": {
                    "type": {
                        "kind": "base", 
                        "name": "unsigned int"
                    }, 
                    "offset": 32
                }
            }, 
            "kind": "struct", 
            "size": 32
        }, 
        "_SERVICE_HEADER": {
            "fields": {
                "Tag": {
                    "type": {
                        "count": 4, 
                        "subtype": {
                            "kind": "base", 
                            "name": "unsigned char"
                        }, 
                        "kind": "array"
                    }, 
                    "offset": 0
                }, 
                "ServiceRecord": {
                    "type": {
                        "kind": "pointer",
                        "subtype": {
                            "kind": "struct",
                            "name": "_SERVICE_RECORD"
                        }
                    },
                    "offset": 16
                }
            }, 
            "kind": "struct", 
            "size": 16
        }, 
        "_SERVICE_RECORD": {
            "fields": {
                "ServiceList": {
                    "type": {
                        "kind": "struct", 
                        "name": "_SERVICE_LIST_ENTRY"
                    }, 
                    "offset": 0
                }, 
                "Tag": {
                    "type": {
                        "count": 4, 
                        "subtype": {
                            "kind": "base", 
                            "name": "unsigned char"
                        }, 
                        "kind": "array"
                    }, 
                    "offset": 32
                }, 
                "DisplayName": {
                    "type": {
                        "kind": "pointer",
                        "subtype": {
                            "kind": "base",
                            "name": "unsigned short"
                        }
                    },
                    "offset": 64
                }, 
                "ServiceProcess": {
                    "type": {
                        "kind": "pointer",
                        "subtype": {
                            "kind": "struct",
                            "name": "_SERVICE_PROCESS"
                        }
                    },
                    "offset": 232
                }, 
                "PrevEntry": {
                    "type": {
                        "kind": "pointer",
                        "subtype": {
                            "kind": "struct",
                            "name": "_SERVICE_RECORD"
                        }
                    },
                    "offset": 16
                }, 
                "Start": {
                    "type": {
                        "kind": "enum", 
                        "name": "StartEnum"
                    }, 
                    "offset": 36
                }, 
                "State": {
                    "type": {
                        "kind": "enum", 
                        "name": "StateEnum"
                    }, 
                    "offset": 76
                }, 
                "ServiceName": {
                    "type": {
                        "kind": "pointer",
                        "subtype": {
                            "kind": "base",
                            "name": "unsigned short"
                        }
                    },
                    "offset": 56
                }, 
                "DriverName": {
                    "type": {
                        "kind": "pointer",
                        "subtype": {
                            "kind": "base",
                            "name": "unsigned short"
                        }
                    },
                    "offset": 232
                }, 
                "Type": {
                    "type": {
                        "kind": "base", 
                        "name": "unsigned long"
                    }, 
                    "offset": 72
                }, 
                "Order": {
                    "type": {
                        "kind": "base", 
                        "name": "unsigned int"
                    }, 
                    "offset": 32
                }
            }, 
            "kind": "struct", 
            "size": 232
        }
    }, 
    "metadata": {
        "producer": {
            "version": "0.0.1", 
            "name": "vtypes_to_json.py", 
            "datetime": "2019-04-17T13:45:16.417006"
        }, 
        "format": "4.1.0"
    }
}

=== DFIRKuiper/Kuiper/kuiper/app/parsers/vol_Parser/volatility/framework/symbols/generic/qemu.json
{
  "symbols": {
  },
  "user_types": {
    "qevm_header": {
      "fields": {
        "magic": {
          "offset": 0,
          "type": {
            "kind": "base",
            "name": "unsigned long"
          }
        },
        "version": {
          "offset": 0,
          "type": {
            "kind": "base",
            "name": "unsigned long"
          }
        }
      },
      "kind": "struct",
      "size": 8
    },
    "qevm_htab": {
      "fields": {
        "index": {
          "offset": 0,
          "type": {
            "kind": "base",
            "name": "unsigned long"
          }
        },
        "n_valid": {
          "offset": 4,
          "type": {
            "kind": "base",
            "name": "unsigned short"
          }
        },
        "n_invalid": {
          "offset": 6,
          "type": {
            "kind": "base",
            "name": "unsigned short"
          }
        }
      },
      "kind": "struct",
      "size": 8
    }
  },
  "enums": {
  },
  "base_types": {
    "unsigned char": {
      "endian": "big",
      "kind": "char",
      "signed": false,
      "size": 1
    },
    "unsigned short": {
      "endian": "big",
      "kind": "int",
      "signed": false,
      "size": 2
    },
    "long": {
      "endian": "big",
      "kind": "int",
      "signed": true,
      "size": 4
    },
    "char": {
      "endian": "big",
      "kind": "char",
      "signed": true,
      "size": 1
    },
    "unsigned long": {
      "endian": "big",
      "kind": "int",
      "signed": false,
      "size": 4
    },
    "long long": {
      "endian": "big",
      "kind": "int",
      "signed": true,
      "size": 8
    },
    "unsigned long long": {
      "endian": "big",
      "kind": "int",
      "signed": false,
      "size": 8
    }
  },
  "metadata": {
    "producer": {
      "version": "0.0.1",
      "name": "ikelos-by-hand",
      "datetime": "2020-01-07T22:59:47"
    },
    "format": "6.1.0"
  }
}
